framework:
    default_locale: 'en'
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - 'ua'

#framework:
#    default_locale: '%locale%'
#    translator:
#        paths:
#            - '%kernel.project_dir%/translations'
#        fallbacks:
#            - '%locale%'