# index:
#     path: /
#     controller: App\Controller\ArticleController::homepage
article:
  path:       /{_locale}/
  controller: App\Controller\ArticleController::changeLocale
  requirements:
    _locale: en|fr|de